# This rule is not used by the project plugin-k3s-cluster itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over plugin-k3s-cluster.kloudlite.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: plugin-k3s-cluster
    app.kubernetes.io/managed-by: kustomize
  name: k3scluster-admin-role
rules:
- apiGroups:
  - plugin-k3s-cluster.kloudlite.github.com
  resources:
  - k3sclusters
  verbs:
  - '*'
- apiGroups:
  - plugin-k3s-cluster.kloudlite.github.com
  resources:
  - k3sclusters/status
  verbs:
  - get
